### 异常的继承结构

异常是程序运行过程中出现的不正常的情况

Java 中的异常能够帮助我们快速定位错误信息

**看图**

##### 异常的分类

编译时异常（凡是Exception下不是RunTimeException以及它的子类的 都是编译时异常），需要预先进行处理程序才能正常运行

运行时异常（RunTimeException以及它的子类），不用对其进行与预先处理.

在写代码的时候，idea爆红了，就是编译时异常

如果idea没有任何错误，程序运行之后出现的异常一般都是运行时异常

### 异常的处理机制

##### throws

将异常交给方法的调者这进行处理，自己本身不处理

处理快捷建：将光标移到出现异常的代码处，alt + 回车 选择抛出

如果一个异常交给了main方法，最终会交给jvm处理，jvm是没有能力处理异常的，程序终止

如果一个方法抛出了异常，调用这个方法的时候也会抛出这个异常

抛出并没有实际解决这个异常，只是甩锅，将这个异常交给了上级(调用者)

```java
public static void main(String[] args) throws ClassNotFoundException {
    Class.forName("");    // 这行代码可能出现异常，我们将异常抛出
}
```

*注意：throws 可以抛出异常的父类（不建议），但是无法抛出异常的子类*

最好是抛出或者处理具体的某个异常

```java
public static void main(String[] args) throws Exception {    // 但是这里可以抛出它的父类
    FileInputStream fis = new FileInputStream("");    // 这里实际抛出的是FileNotFoundException
}
```

*throws可以抛出多个异常*

```java
public static void main(String[] args) throws FileNotFoundException, ClassNotFoundException {
    FileInputStream fis = new FileInputStream("");
    Class.forName("");
}

// 也可以一次抛出他们的共同的父类
public static void main(String[] args) throws Exception {
    FileInputStream fis = new FileInputStream("");
    Class.forName("");
}
```

*使用throws抛出异常，出现异常代码 之后的代码无法继续执行*

##### try catch

对出现的异常进行处理

```java
public static void main(String[] args) {
    try {
        Class.forName("");    // 这里可能会出现异常，需要进行处理，我们选择抓取
    } catch (ClassNotFoundException e) {
        // 注意，不要使用idea自动生成的处理方式，我们不想因为一个小小的异常而终止整个程序，所以处理方式要改变
        e.printStackTrace();
    }
}
```

*try catch可以抓取出现异常的父类*

但是不建议直接抓取所有异常的父类

```java
public static void main(String[] args) {
    try {
        Class.forName("");
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

*try catch 抓取多个异常*

```java
try {
    Class.forName("");
    FileInputStream fis = new FileInputStream("");
} catch (FileNotFoundException e) {
    e.printStackTrace();
} catch (ClassNotFoundException e) {
    e.printStackTrace();
}

// 同样可以直接抓取他们共同的父类
public static void main(String[] args) {
    try {
        Class.forName("");
        FileInputStream fis = new FileInputStream("");
    } catch (Exception e) {
        e.printStackTrace();
    } 
}
```

*Java8新特性*

jdk8可以在一个catch（）里面抓取多个异常

```java
public static void main(String[] args) {
    try {
        Class.forName("");
        FileInputStream fis = new FileInputStream("");
    } catch (FileNotFoundException | ClassNotFoundException e) {        // 可以将多个异常放到一个catch语句块中
        e.printStackTrace();
    } 
}
```

##### finally

在finally语句块中的代码一定能够执行（使用System.exit() 不行）

```java
public static void main(String[] args) {
    try {
        Class.forName("");
    } catch (Exception e) {
        return;
    }finally {
        System.out.println("finally");        // 这里的代码是一定能够执行的
    }
}
```

*可以将一些资源的释放放到finally语句块中执行*

```java
FileInputStream fis = null;
try {
    fis = new FileInputStream("");
} catch (FileNotFoundException e) {
    e.printStackTrace();
}finally {
    // 将资源的释放放在finally中执行
    if(fis != null){
        try {
            fis.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

**注意：如果方法是引用数据类型，可以在finally中改变（String不行）**

*异常可以有什么结构*

```java
try{}catch(){}
try{}finally{}
try{}catch(){}finally{}
```

### 自定义异常

##### 如何定义

新建一个类继承Exception或者RunTimeException，重写最上面的两个方法

```java
public class UsernameAndPasswordException extends Exception{
    public UsernameAndPasswordException() {
        super();
    }
    public UsernameAndPasswordException(String message) {
        super(message);
    }
}
```

##### throw

使用throw可以抛出一个异常

如果是自己手动抛出的异常 用throw抛出的异常，一般都是提醒调用者，所以都是抛出

```java
public static void login(String username, String password) throws UsernameAndPasswordException {
    // 如果用户名和密码都是admin就没问题
    if("admin".equals(username) && "admin".equals(password)){
        System.out.println("登录成功");
    }else {
        throw new UsernameAndPasswordException("用户名密码错误");        // 使用throw抛出一个异常
    }
}
```

##### 异常的两个方法

```java
printStackTrace()            // 打印堆栈跟踪信息（常用）
String getMessage()            // 返回此可抛出对象的详细消息字符串
```
